title: Nik Greb, Walla Walla
description: Mathematics-Statistics Major with Physics Minor from Whitman College, experienced in data analysis, 
modeling, and inference. Skilled in probability theory, optimization, and statistical software (R, Python). 
Collaborative researcher with expertise in real-world data analysis. Strong communicator, distilling complex 
concepts into actionable insights. Seeking opportunities at the intersection of mathematics, statistics, and 
finance, healthcare, or technology.







